_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.4
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 16
epochs:
    value: 5
input_size:
    value:
        - 224
        - 224
learning_rate:
    value: 0.0001
loss:
    value: CrossEntropyLoss
model:
    value: CNN_FD_Classifier
optimizer:
    value: Adam
