_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.4
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 5e-05
